// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.12
// source: todoist.proto

package apiv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TodoistWebhookRequest represents a request to the Todoist webhook endpoint
type TodoistWebhookRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// event_name is the name of the event (e.g., "item:added", "item:updated")
	EventName string `protobuf:"bytes,1,opt,name=event_name,json=eventName,proto3" json:"event_name,omitempty"`
	// user_id is the ID of the user who triggered the event
	UserId string `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	// event_data contains the event data as a JSON string
	EventData string `protobuf:"bytes,3,opt,name=event_data,json=eventData,proto3" json:"event_data,omitempty"`
	// version is the version of the webhook payload
	Version string `protobuf:"bytes,4,opt,name=version,proto3" json:"version,omitempty"`
}

func (x *TodoistWebhookRequest) Reset() {
	*x = TodoistWebhookRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_todoist_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TodoistWebhookRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TodoistWebhookRequest) ProtoMessage() {}

func (x *TodoistWebhookRequest) ProtoReflect() protoreflect.Message {
	mi := &file_todoist_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TodoistWebhookRequest.ProtoReflect.Descriptor instead.
func (*TodoistWebhookRequest) Descriptor() ([]byte, []int) {
	return file_todoist_proto_rawDescGZIP(), []int{0}
}

func (x *TodoistWebhookRequest) GetEventName() string {
	if x != nil {
		return x.EventName
	}
	return ""
}

func (x *TodoistWebhookRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *TodoistWebhookRequest) GetEventData() string {
	if x != nil {
		return x.EventData
	}
	return ""
}

func (x *TodoistWebhookRequest) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

// TodoistWebhookResponse represents a response from the Todoist webhook endpoint
type TodoistWebhookResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	// success indicates whether the webhook was processed successfully
	Success bool `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	// message contains a human-readable message about the result
	Message string `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *TodoistWebhookResponse) Reset() {
	*x = TodoistWebhookResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_todoist_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TodoistWebhookResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TodoistWebhookResponse) ProtoMessage() {}

func (x *TodoistWebhookResponse) ProtoReflect() protoreflect.Message {
	mi := &file_todoist_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TodoistWebhookResponse.ProtoReflect.Descriptor instead.
func (*TodoistWebhookResponse) Descriptor() ([]byte, []int) {
	return file_todoist_proto_rawDescGZIP(), []int{1}
}

func (x *TodoistWebhookResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *TodoistWebhookResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_todoist_proto protoreflect.FileDescriptor

var file_todoist_proto_rawDesc = []byte{
	0x0a, 0x0d, 0x74, 0x6f, 0x64, 0x6f, 0x69, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12,
	0x0d, 0x63, 0x68, 0x65, 0x72, 0x72, 0x79, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x22, 0x88,
	0x01, 0x0a, 0x15, 0x54, 0x6f, 0x64, 0x6f, 0x69, 0x73, 0x74, 0x57, 0x65, 0x62, 0x68, 0x6f, 0x6f,
	0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x76, 0x65, 0x6e,
	0x74, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x76,
	0x65, 0x6e, 0x74, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x75, 0x73, 0x65, 0x72, 0x5f,
	0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x75, 0x73, 0x65, 0x72, 0x49, 0x64,
	0x12, 0x1d, 0x0a, 0x0a, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x5f, 0x64, 0x61, 0x74, 0x61, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x65, 0x76, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12,
	0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x4c, 0x0a, 0x16, 0x54, 0x6f, 0x64,
	0x6f, 0x69, 0x73, 0x74, 0x57, 0x65, 0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x73, 0x75, 0x63, 0x63, 0x65, 0x73, 0x73, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x32, 0x6f, 0x0a, 0x0e, 0x54, 0x6f, 0x64, 0x6f, 0x69,
	0x73, 0x74, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x5d, 0x0a, 0x0e, 0x50, 0x72, 0x6f,
	0x63, 0x65, 0x73, 0x73, 0x57, 0x65, 0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x12, 0x24, 0x2e, 0x63, 0x68,
	0x65, 0x72, 0x72, 0x79, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76, 0x31, 0x2e, 0x54, 0x6f, 0x64, 0x6f,
	0x69, 0x73, 0x74, 0x57, 0x65, 0x62, 0x68, 0x6f, 0x6f, 0x6b, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x1a, 0x25, 0x2e, 0x63, 0x68, 0x65, 0x72, 0x72, 0x79, 0x2e, 0x61, 0x70, 0x69, 0x2e, 0x76,
	0x31, 0x2e, 0x54, 0x6f, 0x64, 0x6f, 0x69, 0x73, 0x74, 0x57, 0x65, 0x62, 0x68, 0x6f, 0x6f, 0x6b,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x21, 0x5a, 0x1f, 0x63, 0x68, 0x65, 0x72,
	0x72, 0x79, 0x5f, 0x62, 0x61, 0x63, 0x6b, 0x65, 0x6e, 0x64, 0x2f, 0x70, 0x6b, 0x67, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x76, 0x31, 0x3b, 0x61, 0x70, 0x69, 0x76, 0x31, 0x62, 0x06, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x33,
}

var (
	file_todoist_proto_rawDescOnce sync.Once
	file_todoist_proto_rawDescData = file_todoist_proto_rawDesc
)

func file_todoist_proto_rawDescGZIP() []byte {
	file_todoist_proto_rawDescOnce.Do(func() {
		file_todoist_proto_rawDescData = protoimpl.X.CompressGZIP(file_todoist_proto_rawDescData)
	})
	return file_todoist_proto_rawDescData
}

var file_todoist_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_todoist_proto_goTypes = []interface{}{
	(*TodoistWebhookRequest)(nil),  // 0: cherry.api.v1.TodoistWebhookRequest
	(*TodoistWebhookResponse)(nil), // 1: cherry.api.v1.TodoistWebhookResponse
}
var file_todoist_proto_depIdxs = []int32{
	0, // 0: cherry.api.v1.TodoistService.ProcessWebhook:input_type -> cherry.api.v1.TodoistWebhookRequest
	1, // 1: cherry.api.v1.TodoistService.ProcessWebhook:output_type -> cherry.api.v1.TodoistWebhookResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_todoist_proto_init() }
func file_todoist_proto_init() {
	if File_todoist_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_todoist_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TodoistWebhookRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_todoist_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TodoistWebhookResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_todoist_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_todoist_proto_goTypes,
		DependencyIndexes: file_todoist_proto_depIdxs,
		MessageInfos:      file_todoist_proto_msgTypes,
	}.Build()
	File_todoist_proto = out.File
	file_todoist_proto_rawDesc = nil
	file_todoist_proto_goTypes = nil
	file_todoist_proto_depIdxs = nil
}
